#!/usr/bin/python3 -u
import logging
# @file pair_tool
# @author Frederich Stine
# @brief host tool for pairing a new key fob
# @date 2023
#
# This source file is part of an example system for MITRE's 2023 Embedded
# CTF (eCTF). This code is being provided only for educational purposes for the
# 2023 MITRE eCTF competition, and may not meet MITRE standards for quality.
# Use this code at your own risk!
#
# @copyright Copyright (c) 2023 The MITRE Corporation

import socket
import argparse
import time

from common import FobConnection
from cryptography.hazmat.primitives import hashes


# @brief Function to send commands to pair
# a new fob.
# @param unpairmed_fob_bridge, bridged serial connection to unpairmed fob
# @param pairmed_fob_bridge, bridged serial connection to pairmed fob
# @param pair_pin, pin used to pair a new fob
def pair(unpaired_fob_bridge, paired_fob_bridge, pair_pin):

    # Connect to both sockets for serial
    # unpaired_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # unpaired_sock.connect(("ectf-net", int(unpaired_fob_bridge)))

    paired_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    paired_sock.connect(("0.0.0.0", int(paired_fob_bridge)))


    # TODO: Change for release
    # unpaired_sock.settimeout(60)
    paired_sock.settimeout(60)

    paired_d = FobConnection(paired_sock)
    # unpaired_d = FobConnection(unpaired_sock)

    paired_d.ecdh_exchange()

    # Send pair commands to both fobs
    paired_d.send_packet(0x4D)
    paired_d.wait_for_ack()

    # todo: not tested beyond this point!
    return

    digest = hashes.Hash(hashes.BLAKE2s(16))
    digest.update(pair_pin.encode('utf-8'))
    pair_pin = digest.finalize()

    paired_d.send_packet(0x50, pair_pin)
    # todo: set longer timeout to let devices do their thing
    paired_d.wait_for_ack()



    # Acknowlege --  if failed, pairing failed
    try:
        pair_success = unpaired_sock.recv(6)
        while len(pair_success) != 6:
            pair_success += unpaired_sock.recv(6 - len(pair_success))

        print(pair_success)
    except socket.timeout:
        print("No Acknowlegement")

    paired_sock.send(b'0x50')

    # Send pin to the paired fob
    pair_pin_bytes = str.encode(pair_pin + "\n")
    unpaired_sock.send(pair_pin_bytes)

    # Set timeout for if pairing fails
    unpaired_sock.settimeout(5)
    # Try to receive data - if failed, pairing failed
    try:
        pair_success = unpaired_sock.recv(6)
        while len(pair_success) != 6:
            pair_success += unpaired_sock.recv(6 - len(pair_success))

        print(pair_success)
    except socket.timeout:
        print("Failed to pair fob")

    return 0


# @brief Main function
#
# Main function handles parsing arguments and passing them to pair
# function.
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--unpaired-fob-bridge",
        help="Bridge for the unpaired fob",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--paired-fob-bridge",
        help="Bridge for the paired fob",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--pair-pin", help="Program PIN", type=str, required=True,
    )

    logging.basicConfig(level=logging.DEBUG)

    args = parser.parse_args()

    pair(args.unpaired_fob_bridge, args.paired_fob_bridge, args.pair_pin)


if __name__ == "__main__":
    main()
